project:
  type: website
  output-dir: docs

website:
  title: "Quarto Sandbox"
  navbar:
    background: "#6A2526"
    text: "#E7E6DA"
    title: false
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: datavis.qmd
        text: Data Visualization
      - about.qmd
  

format:
  html:
    grid:
      body-width: 1200px
    include-before-body: header.html
    theme:
      - lux
      - brand
    css: styles.css
    toc: false



