---
title: "How We Collected the Data"
---

The data in this dataset was collected primarily from SPT's public Wordpress, linked at the bottom of this page. Year, Season, Show, and  Times Performed data all came from this site. 

SPT's Youtube channel was used to collect cast size data, and to verify the accuracy of the data collected from the Wordpress. SPT's Youtube is not fully up to date, nor does it contain video of every performance, and so presents a less complete performance record. The inconsistancy of data on the Youtube channel is the reason that cast size data is not availabe for every performance in the dataset, and is not listed in the table on the homepage. 

Genre data was determined based on the general consensus around the genre of each play, and was not sourced from SPT's Wordpress or Youtube. Shakespeare plays were classified as comedies, tragedies, histories, or tragedy-comedies, the term used in this dataset to describe his so called "problem plays", which do not fit neatly into the other three main genres. This was done to allow for the categorization of other, non-shakespearean plays alongside plays like "The Winter's Tale" as being similarly generically complex. The "Other" category was used for satires, musicals, collections of short plays, and other performances that do not fit cleanly into the other four main genres used. 

Author data was available online and in publications of each play. Shows which had more than one author were classified as "Multiple Authors" and shows which had an unknown author were classified as "Unknown Author". Shows which were written, in large part or in full, by members of the troupe were classifed as "Self Written".

For now, these are the current primary feilds in the dataset, but more data may be added in the future. Areas that may be expanded upon include cast size, run time, director, and other data that may be available or become available in the future. 